### ISSUE TITLE
Fix Compilation failure on esp32 Core Version 3.0.0

### ISSUE THREAD

**Issue by Daedelos** [luc-github/ESP32SSDP#41]
**Describe the bug**
Changes in rel 3.0.0 of esp32 result in compilation failures

. . . \libraries\ESP32SSDP-1.2.1\src\ESP32SSDP.cpp:158:5: error: 'tcpip_adapter_ip_info_t' was not declared in this scope; did you mean 'tcpip_adapter_if_t'?
  158 |     tcpip_adapter_ip_info_t ip;
      |     ^~~~~~~~~~~~~~~~~~~~~~~

. . . \libraries\ESP32SSDP-1.2.1\src\ESP32SSDP.cpp:160:13: error: 'tcpip_adapter_get_ip_info' was not declared in this scope; did you mean 'tcpip_adapter_if_t'?
  160 |         if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip)) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~

**To Reproduce**
Use esp32 rel 3.0.0

**Expected behavior**
Compilation without errors

**Firmware:**
- ESP core version: 3.0.0
- Library Version: 1.21
- Wifi mode:STA

**Board used (please complete the following information):**
 - MCU: doit esp32

**Comment by luc-github** [comment]
>Expected behavior
Compilation without errors

Sorry wrong expectation :  https://esp3d.io/esp3d/v3.x/installation/arduino/index.html
Currently only esp32 2.0.8 is supported

esp32 3.0.0 release  is a break changes and I am waiting platformio is also supporting fully the esp32 3.0.0 release to work more on it - I have started already https://github.com/luc-github/ESP3D/tree/arduino-esp32-3.0.0-devt and even reported some issues, but this is currently a work in progress because libraries dependencies need also to be updated , and because it is breaking change I need to be sure everything is up to date.

**Comment by luc-github** [comment]
you can give a try to https://github.com/luc-github/ESP3D/tree/arduino-esp32-3.0.0-devt/libraries/ESP32SSDP-2.0.0 but I did not tested with latest release

**Comment by Daedelos** [comment]
Thanks. I'll give it a go.

**Comment by luc-github** [comment]
Please, let me know your feedback on it, sample code is limited for stress tests.
Also, because it seems esp32 3.0 porting to platformio has some issue, and can be delayed, I will work on SSDP 2.0 next week with arduino only support, the code base will be the one I gave you, so I would appreciate your feed back on real usage than sample code

**Comment by luc-github** [comment]
@Daedelos I did this branch for the 2.0 : https://github.com/luc-github/ESP32SSDP/tree/v2.x 
I have compiled the sample code with esp32 core v 3.0.0 and so far it is ok on my side

**Comment by Daedelos** [comment]
Looking good. I have incorporated the coe into one of my larger projects and it is working well. I will further testing. Many thanks.

**Comment by luc-github** [comment]
cool - I am waiting your final feedback then to close the ticket and do the release of 2.0.0 - thank you for your help

**Comment by Daedelos** [comment]
I've been using it on various clients for over 12 hours with no problems.

**Comment by luc-github** [comment]
Cool, I will do a release for version 2.0 tomorrow then.

I really appreciate the feedback - thank you.

**Comment by luc-github** [comment]
Release of 2.0.0 done https://github.com/luc-github/ESP32SSDP/releases/tag/2.0.0 in branch https://github.com/luc-github/ESP32SSDP/tree/v2.x
previous version is now https://github.com/luc-github/ESP32SSDP/tree/1.2.2 in branch https://github.com/luc-github/ESP32SSDP/tree/v1.x
